{
 "title": "Business",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producing Rate  - Wikipedia changes / 1min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(recentChanges_onNext_delay_seconds_count[1m])",
     "legendFormat": "changes"
    }
   ]
  },
  {
   "title": "Consuming Rate  - Wikipedia changes / 1min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(recentChanges_requested_sum[1m])",
     "legendFormat": "changes"
    }
   ]
  },
  {
   "title": "Processing completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(processing_flow_duration_seconds_count{status=\"completed\"}[1m])",
     "legendFormat": "Processing completed"
    }
   ]
  },
  {
   "title": "Processing completedEmpty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(processing_flow_duration_seconds_count{status=\"completedEmpty\"}[1m])",
     "legendFormat": "Processing completedEmpty"
    }
   ]
  },
  {
   "title": "Processing errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(processing_flow_duration_seconds_count{status=\"error\"}[1m])",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(recentChanges_flow_duration_seconds_count{status=\"cancelled\"}[1m])",
     "legendFormat": "Cancelled"
    }
   ]
  }
 ]
}